### ISSUE TITLE
Duplicate Sectors Entities after migration from OpenCTI 3 to 4

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#1095]
## Description

When I migrated from 3 to 4 using the migration script, I noticed that the Subsector entities were duplicated.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04 LTS
2. OpenCTI version: OpenCTI 4.0
3. OpenCTI client: frontend
4. Other environment details: migrated from 3 to 4 using the migration script

## Reproducible Steps

Steps to create the smallest reproducible scenario:

I haven't tried to reproduce it as the migration took days.

## Expected Output

Each subsector would be unique.

## Actual Output

See attached image.
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }
![image](https://user-images.githubusercontent.com/8810661/108251292-36ad7c80-7125-11eb-8dca-3786670c6831.png)

**Comment by SamuelHassine** [comment]
Hello @smclinden,

You should use the latest version of OpenCTI to make the migration and not the version 4.0. This is a bug and it has been solved. Are you able to start fresh with the latest OpenCTI 4?

Kind regards,
Samuel

**Comment by smclinden** [comment]
Samuel:

Unfortunately, that would not be practical. For whatever reason, the first migration took over a month and 99.9% of that was clearing the RabbitMQ queue on the 4.0 server.

Unless I am able to figure out why that took so long, and substantially improve the migration time, I can't afford to be down for another month.

**Comment by smclinden** [comment]
I suspect that it would be more practical to deduplicate the data in Elasticsearch.

**Comment by SamuelHassine** [comment]
Hey @smclinden,

We have fixed a lot of bugs around deduplication and I think this should do the trick:

1. Upgrade your platform to the latest version
2. Reset the connector state of the "OpenCTI dataset" to force an upgrade
3. All sectors will be automatically merged together

Kind regards,
Samuel

**Comment by smclinden** [comment]
I'm running the latest release version, but the reset had no effect.

**Comment by SamuelHassine** [comment]
Hello @smclinden,

Are you able to de-deplicate entities using the "Data curation" interface? You can merge duplicate sectors together.

Kind regards,
Samuel

**Comment by smclinden** [comment]
It appears so. The duplicates appeared to be a result of importing data from both AlienVault and Crowdstrike.

**Comment by smclinden** [comment]
I take that back. I can merge sectors in Data>Curation but the duplicates still appear in Entities>Sectors. As an example, there are two instances of Dissidents with the same STIX IDs.

**Comment by SamuelHassine** [comment]
Ok, I understand. I think it's linked to the relationships and not the sectors themself. Do you see duplicates in Data curation or just in the sectors pages ? The best way would be to unlink sector/subsectors using the unlink button in the parent sector itself. And then replay the OpenCTI datasets connector, it will recreate all missing relationship between parent sectors and subsectors.

**Comment by smclinden** [comment]
Only in Entities>Sectors. 

In Data Curation different agencies/authors use different names for the same thing (which is a different issue from sector duplication).

In particular (and not to pick on anyone) Agence Nationale has "Central administration and government", "Government and administrations" and "Culture" and "Culture and entertainment" (to list a few). These don't, cleanly, jive with what ALienvault or Crowdstrike use.

**Comment by SamuelHassine** [comment]
To avoid duplicates on sectors when a connector is creating new ones. We will add the aliases by default in our dataset. If you have some ideas (to add aliases to our sectors), please open issue here: https://github.com/OpenCTI-Platform/datasets.
